#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';  // Line 8

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$code = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    $output = new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $code);

exit($code);
